server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sber
          uri: lb://samokat
          predicates:
            - Path=/api/best
            - Method=GET

        - id: itmo
          uri: lb://delivery
          predicates:
            - Path=/api/product
            - Method=GET

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}