server:
  port: 0
  servlet:
    context-path: /api

spring:
  application:
    name: delivery

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}